### ISSUE TITLE
Coach Registration page

### ISSUE THREAD

**Issue by DagMT** [dagim-shimelis/Find-a-Tutor#11]
- [x] Coach registration form which will accept information of coach
- [x] Stores the coach's data to the Vuex store
- [x] Add form validation to the registration form

**Comment by ghost** [comment]
I will handle the first task of this issue by the end of the day.

**Comment by Andybegu** [comment]
i will handle the second and the third task

**Comment by DagMT** [comment]
Good collaboration on the coach registration page, good job guys
